---
# tasks file for java

- name: Install Java 8
  yum:
    name: java-1.8.0
    state: present
    update_cache: yes
  become: True

- name: Remove Java 7
  yum:
    name: java-1.7.0-openjdk
    state: absent
    update_cache: yes